
NumPy is a powerful library in Python for numerical computing. It provides an array object that is efficient for handling large datasets and offers a wide range of mathematical functions for array manipulation, linear algebra, Fourier transforms, random number generation, and more. Here's a brief overview of some key features and how to use them:

Importing NumPy:
To start using NumPy, you need to import the library:

In [2]:
import numpy as np


Creating NumPy Arrays:
NumPy arrays, also known as ndarrays, are the primary data structure in NumPy. You can create arrays using various methods:

In [27]:
# From a list
arr1 = np.array([1, 2, 3, 4, 5])

# From a nested list (2D array)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# Using built-in functions
arr3 = np.zeros((3, 4))  # 3x4 array filled with zeros
arr4 = np.ones((2, 2))   # 2x2 array filled with ones
arr5 = np.arange(11, 38, 7)  # Array of numbers from 0 to 10 (exclusive) with step 2
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
arr4

array([[1., 1.],
       [1., 1.]])

In [29]:
arr5

array([11, 18, 25, 32])

Array Operations:
NumPy arrays allow for efficient element-wise operations and broadcasting:

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise operations
c = a + b   # [5, 7, 9]
d = a * b   # [4, 10, 18]

# Broadcasting
e = a + 1   # [2, 3, 4]
f = a * 2   # [2, 4, 6]


Array Indexing and Slicing:
You can access and manipulate array elements using indexing and slicing:

In [5]:
arr = np.array([1, 2, 3, 4, 5])

# Accessing elements
print(arr[0])   # 1
print(arr[2])   # 3

# Slicing
print(arr[1:4])   # [2, 3, 4]
print(arr[:3])    # [1, 2, 3]
print(arr[3:])    # [4, 5]

# 2D array indexing
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d[1, 2])   # 6
print(arr2d[:, 1])   # [2, 5] (selects all rows, second column)


1
3
[2 3 4]
[1 2 3]
[4 5]
6
[2 5]


Mathematical Functions:
NumPy provides a wide range of mathematical functions that can be applied to arrays:

In [10]:
arr = np.array([-121, .5, 3, 4, 11])

# Basic functions
print(np.mean(arr))       # Mean: 3.0
print(np.sum(arr))        # Sum: 15
print(np.max(arr))        # Maximum: 5
print(np.min(arr))        # Minimum: 1
print(np.std(arr))        # Standard deviation: 1.41421356

# Trigonometric functions
print(np.arcsin(arr))        # Sine of each element

# Linear algebra functions
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))


-20.5
-102.5
11.0
-121.0
50.37062636100528
[       nan 0.52359878        nan        nan        nan]
[[19 22]
 [43 50]]


C:\Users\ronan\AppData\Local\Temp\ipykernel_4152\1362937082.py:11: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(arr))        # Sine of each element


0.52359878  rads in degrees

In [11]:

radians = 0.52359878
degrees = np.degrees(radians)
print(degrees)

30.0000002521989
